[package]
name = "workspace_opener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = {version = "0.25", features=  ["event-stream"] }
tui = "0.19.0"
log = "0.4.17"
simplelog = "0.12.0"
