on:
  release:
    types: [created]

jobs:
  release:
     name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: tar.gz
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
    steps:
      - uses: actions/checkout@main
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          TOOLCHAIN_VERSION: 1.64.0
    name: release windows msvc
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          cargo build --release
      - name: tar
        run: tar --directory=target/release -cf archive.tar.gz workspace_opener.exe
      - name: upload
        run: |
          $id = gh api -H "Accept: application/vnd.github+json" /repos/Sh-u/workspace_opener/releases/tags/${{ github.ref_name }} --jq .id
          curl --fail-with-body -sS  -X POST --data-binary "@archive.tar.gz" -H 'Content-Type: application/octet-stream' -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' "https://uploads.github.com/repos/Sh-u/workspace_opener/releases/$id/assets?name=workspace_opener_${{ github.ref_name }}_x86_64-pc-windows-msvc.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}